/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nicro' at '05.10.17 20:25' with Gradle 2.14.1
 *
 * @author nicro, @date 05.10.17 20:25
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
